project:
  type: website
  output-dir: docs
  preview: 
    browser: true

website:
  
  title: "Cacical 「カシカル」"
  description: '作成したグラフを生成スクリプトとともにフリーで公開しています。'
  favicon:  './fig/logo.png'

  site-url: 'https://cacical.jp'
  site-path: '/'

  navbar:
    #logo: './fig/cacical_logo.png'
    #logo-alt: 'logo.'
    title: '[カシカル]{.titlefont}'
    pinned: true
    collapse-below: lg
    left:
      - text: '**ノート**'
        href: ./contents/list_memo.qmd
      
      - text: '**科学・技術**'
        href: ./contents/list_science.qmd

      - text: '**社会・経済**'
        href: ./contents/list_society.qmd

      - text: '**地球環境**'
        href: ./contents/list_environment.qmd

      - text: '**About**'
        href: about.qmd

    tools:
      - icon: github
        href: https://github.com/iwahibari


  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Info**  2025 8/28 AMBERのアトムマスクに関しての記事を公開しました。"
    type: info
    position: below-navbar

  back-to-top-navigation: true
  #bread-crumbs: true

  # page-footer: 
  #   left: "Copyright 2025, iwahibari" 
  #   right: 
  #     - icon: github
  #       href: https://github.com/iwahibari
  #     - icon: twitter 
  #       href: https://twitter.com/ 


format:
  html:
    grid:
      body-width: 800px
    include-in-header: gtm_code_head.html
    theme: 
      light: [default, ./style/costom-light.scss]
      dark: [default, ./style/costom-dark.scss]
    toc: true
    toc-depth: 5
    toc-expand: true
    highlight-style: arrow-dark
    fontsize: 18px
    linestretch: 1.8
  
    
lang: ja
