project:
  type: website
  output-dir: docs
  preview: 
    browser: true

website:
  
  title: "Cacical 「カシカル」"
  description: '作成したグラフをスクリプトとともにフリーで公開しています。'
  favicon:  './fig/favicon.jpg'

  site-url: 'https://cacical.jp'
  site-path: '/'

  navbar:
    pinned: true
    #logo: './fig/cacical_logo.png'
    #logo-alt: 'logo.'
    title: '[カシカル]{.titlefont}'
    collapse-below: lg
    left:
      - text: 'ノート'
        href: ./contents/list_memo.qmd
      
      - text: 'サイエンス'
        href: ./contents/list_science.qmd

      - text: 'ソーシャル'
        href: ./contents/list_society.qmd

      - text: 'サステナブル'
        href: ./contents/list_environment.qmd

      - text: 'About'
        href: about.qmd

    tools:
      - icon: github
        href: https://github.com/iwahibari

  back-to-top-navigation: true

  open-graph: true
  twitter-card: true
  #cookie-consent:
  #  prefs-text: cookieの設定


format:
  html:
    grid:
      body-width: 800px
    include-in-header: gtm_code_head.html
    theme: 
      light: [default, ./style/costom-light.scss]
      #dark: [default, ./style/costom-dark.scss]
    toc: true
    toc-depth: 5
    toc-expand: true
    highlight-style: arrow-dark
    fontsize: 18px
    linestretch: 1.8
  
    
lang: ja