---
pagetitle: "公衆トイレマップ"
format:
  dashboard: 
    orientation: columns
---

```{r}
#| echo: false
#| output: false

# ライブラリの読み込み
library(leaflet)
library(leaflet.extras)
library(DT)
library(crosstalk)
library(dplyr)

# データの読み込み
toilet_data <- read.csv('https://www.opendata.metro.tokyo.lg.jp/edogawa/131237_public_toilet.csv', fileEncoding = "UTF-8", stringsAsFactors = FALSE)

# 必要なデータを選択・加工
toilet_data_clean <- toilet_data %>%
  select(
    name = 名称,
    location = 設置位置,
    wheelchair = 車椅子使用者用トイレ有無,
    lat = 緯度,
    lon = 経度
  ) %>%
  mutate(
    lat = as.numeric(lat),
    lon = as.numeric(lon),
  ) %>%
  filter(!is.na(lat) & !is.na(lon)) %>%
  select(name, location, wheelchair, lat, lon)

shared_toilet_data <- SharedData$new(toilet_data_clean, group = "toilet_selection")

total_toilets <- nrow(toilet_data_clean)
wheelchair_toilets <- toilet_data_clean %>%
  filter(wheelchair == "有") %>%
  nrow()

```

## Column

### Row
```{r}
#| content: valuebox
#| title: 江戸川区の公衆トイレ数

list(
    color = 'blue',
    value = total_toilets
)

```

```{r}
#| content: valuebox
#| title: 車椅子対応の公衆トイレ数

list(
    value = wheelchair_toilets
)

```

### Row

```{r}
#| title: 江戸川区の公衆トイレ
datatable(
  shared_toilet_data,
  colnames = c("名称", "設置位置", "車いす用", "lat", "lon"),
  extensions = 'Scroller',
  options = list(
    columnDefs = list(list(visible = FALSE, targets = c('lat', 'lon'))),
    deferRender = TRUE,
    dom = "frtiS",
    scrollCollapse = TRUE
  ),
  selection = 'single',
  width = "100%"
)

```

## Column

```{r map}
#| echo: false
#| title: 公衆トイレマップ

pal <- colorFactor(
  palette = c('red', 'blue'),
  domain = shared_toilet_data$wheelchair
)

map <- leaflet(shared_toilet_data) %>%
  addTiles() %>%
  setView(lng = 139.86, lat = 35.7, zoom = 12) %>%
  #addMarkers(lng = ~lon, lat = ~lat, popup = ~name, color = ~pal(category))
  addCircles(lng = ~lon, lat = ~lat, radius=5 , weight=0, fillColor = ~pal(wheelchair), fillOpacity = 1) %>%
  addCircles(lng = ~lon, lat = ~lat, popup = ~name, radius=70 , weight=0, fillColor = ~pal(wheelchair), fillOpacity = 0.3) %>%
  addControlGPS(
    options = gpsOptions(
      position = "topleft",
      activate = TRUE, 
      autoCenter = TRUE,
      setView = TRUE))
#  addMarkers(lng = ~lon, lat = ~lat)
activateGPS(map)
```
